
package org.mdr.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AccreditorWebService", targetNamespace = "http://mdr.org/wsdl", wsdlLocation = "http://127.0.0.1:4204/Accreditor?wsdl")
public class AccreditorWebService
    extends Service
{

    private final static URL ACCREDITORWEBSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.mdr.wsdl.AccreditorWebService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.mdr.wsdl.AccreditorWebService.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1:4204/Accreditor?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:4204/Accreditor?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ACCREDITORWEBSERVICE_WSDL_LOCATION = url;
    }

    public AccreditorWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccreditorWebService() {
        super(ACCREDITORWEBSERVICE_WSDL_LOCATION, new QName("http://mdr.org/wsdl", "AccreditorWebService"));
    }

    /**
     * 
     * @return
     *     returns AccreditorService
     */
    @WebEndpoint(name = "AccreditorPort")
    public AccreditorService getAccreditorPort() {
        return super.getPort(new QName("http://mdr.org/wsdl", "AccreditorPort"), AccreditorService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccreditorService
     */
    @WebEndpoint(name = "AccreditorPort")
    public AccreditorService getAccreditorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mdr.org/wsdl", "AccreditorPort"), AccreditorService.class, features);
    }

}
