
package org.mdr.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AccreditorService", targetNamespace = "http://mdr.org/wsdl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AccreditorService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @throws RepositoryException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createSteward", targetNamespace = "http://mdr.org/wsdl", className = "org.mdr.wsdl.CreateSteward")
    @ResponseWrapper(localName = "createStewardResponse", targetNamespace = "http://mdr.org/wsdl", className = "org.mdr.wsdl.CreateStewardResponse")
    public void createSteward(
        @WebParam(name = "arg0", targetNamespace = "")
        Steward arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws RepositoryException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws RepositoryException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createSubmitter", targetNamespace = "http://mdr.org/wsdl", className = "org.mdr.wsdl.CreateSubmitter")
    @ResponseWrapper(localName = "createSubmitterResponse", targetNamespace = "http://mdr.org/wsdl", className = "org.mdr.wsdl.CreateSubmitterResponse")
    public void createSubmitter(
        @WebParam(name = "arg0", targetNamespace = "")
        Submitter arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws RepositoryException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws RepositoryException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createRegistrar", targetNamespace = "http://mdr.org/wsdl", className = "org.mdr.wsdl.CreateRegistrar")
    @ResponseWrapper(localName = "createRegistrarResponse", targetNamespace = "http://mdr.org/wsdl", className = "org.mdr.wsdl.CreateRegistrarResponse")
    public void createRegistrar(
        @WebParam(name = "arg0", targetNamespace = "")
        Registrar arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws RepositoryException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns org.mdr.wsdl.Contact
     * @throws RepositoryAuthenticationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authenticate", targetNamespace = "http://mdr.org/wsdl", className = "org.mdr.wsdl.Authenticate")
    @ResponseWrapper(localName = "authenticateResponse", targetNamespace = "http://mdr.org/wsdl", className = "org.mdr.wsdl.AuthenticateResponse")
    public Contact authenticate(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws RepositoryAuthenticationException_Exception
    ;

    /**
     * 
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws RepositoryException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateContactInfo", targetNamespace = "http://mdr.org/wsdl", className = "org.mdr.wsdl.UpdateContactInfo")
    @ResponseWrapper(localName = "updateContactInfoResponse", targetNamespace = "http://mdr.org/wsdl", className = "org.mdr.wsdl.UpdateContactInfoResponse")
    public void updateContactInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4)
        throws RepositoryException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws RepositoryException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updatePasswordForUser", targetNamespace = "http://mdr.org/wsdl", className = "org.mdr.wsdl.UpdatePasswordForUser")
    @ResponseWrapper(localName = "updatePasswordForUserResponse", targetNamespace = "http://mdr.org/wsdl", className = "org.mdr.wsdl.UpdatePasswordForUserResponse")
    public void updatePasswordForUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws RepositoryException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns org.mdr.wsdl.Contact
     * @throws RepositoryException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getContactInfo", targetNamespace = "http://mdr.org/wsdl", className = "org.mdr.wsdl.GetContactInfo")
    @ResponseWrapper(localName = "getContactInfoResponse", targetNamespace = "http://mdr.org/wsdl", className = "org.mdr.wsdl.GetContactInfoResponse")
    public Contact getContactInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws RepositoryException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws RepositoryException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createReadOnlyUser", targetNamespace = "http://mdr.org/wsdl", className = "org.mdr.wsdl.CreateReadOnlyUser")
    @ResponseWrapper(localName = "createReadOnlyUserResponse", targetNamespace = "http://mdr.org/wsdl", className = "org.mdr.wsdl.CreateReadOnlyUserResponse")
    public void createReadOnlyUser(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws RepositoryException_Exception
    ;

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updatePassword", targetNamespace = "http://mdr.org/wsdl", className = "org.mdr.wsdl.UpdatePassword")
    @ResponseWrapper(localName = "updatePasswordResponse", targetNamespace = "http://mdr.org/wsdl", className = "org.mdr.wsdl.UpdatePasswordResponse")
    public void updatePassword(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.mdr.wsdl.Contact
     * @throws RepositoryException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSupervisor", targetNamespace = "http://mdr.org/wsdl", className = "org.mdr.wsdl.GetSupervisor")
    @ResponseWrapper(localName = "getSupervisorResponse", targetNamespace = "http://mdr.org/wsdl", className = "org.mdr.wsdl.GetSupervisorResponse")
    public Contact getSupervisor(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws RepositoryException_Exception
    ;

}
