
package org.mdr.wsdl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AdministrationService", targetNamespace = "http://mdr.org/wsdl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AdministrationService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @throws RepositoryException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "changeVisibility", targetNamespace = "http://mdr.org/wsdl", className = "org.mdr.wsdl.ChangeVisibility")
    @ResponseWrapper(localName = "changeVisibilityResponse", targetNamespace = "http://mdr.org/wsdl", className = "org.mdr.wsdl.ChangeVisibilityResponse")
    public void changeVisibility(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws RepositoryException_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<org.mdr.wsdl.KeptItem>
     * @throws RepositoryException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryItems", targetNamespace = "http://mdr.org/wsdl", className = "org.mdr.wsdl.QueryItems")
    @ResponseWrapper(localName = "queryItemsResponse", targetNamespace = "http://mdr.org/wsdl", className = "org.mdr.wsdl.QueryItemsResponse")
    public List<KeptItem> queryItems(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        XMLGregorianCalendar arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        XMLGregorianCalendar arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3)
        throws RepositoryException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws RepositoryException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "changeStatus", targetNamespace = "http://mdr.org/wsdl", className = "org.mdr.wsdl.ChangeStatus")
    @ResponseWrapper(localName = "changeStatusResponse", targetNamespace = "http://mdr.org/wsdl", className = "org.mdr.wsdl.ChangeStatusResponse")
    public void changeStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws RepositoryException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createKeptItemHeader", targetNamespace = "http://mdr.org/wsdl", className = "org.mdr.wsdl.CreateKeptItemHeader")
    @ResponseWrapper(localName = "createKeptItemHeaderResponse", targetNamespace = "http://mdr.org/wsdl", className = "org.mdr.wsdl.CreateKeptItemHeaderResponse")
    public Long createKeptItemHeader(
        @WebParam(name = "arg0", targetNamespace = "")
        KeptItemHeader arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns long
     * @throws RepositoryException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registerAndUpload", targetNamespace = "http://mdr.org/wsdl", className = "org.mdr.wsdl.RegisterAndUpload")
    @ResponseWrapper(localName = "registerAndUploadResponse", targetNamespace = "http://mdr.org/wsdl", className = "org.mdr.wsdl.RegisterAndUploadResponse")
    public long registerAndUpload(
        @WebParam(name = "arg0", targetNamespace = "")
        KeptItem arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        byte[] arg1)
        throws RepositoryException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     * @throws RepositoryException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getModel", targetNamespace = "http://mdr.org/wsdl", className = "org.mdr.wsdl.GetModel")
    @ResponseWrapper(localName = "getModelResponse", targetNamespace = "http://mdr.org/wsdl", className = "org.mdr.wsdl.GetModelResponse")
    public byte[] getModel(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0)
        throws RepositoryException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns long
     * @throws RepositoryException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "register", targetNamespace = "http://mdr.org/wsdl", className = "org.mdr.wsdl.Register")
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://mdr.org/wsdl", className = "org.mdr.wsdl.RegisterResponse")
    public long register(
        @WebParam(name = "arg0", targetNamespace = "")
        KeptItem arg0)
        throws RepositoryException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns org.mdr.wsdl.KeptItem
     * @throws RepositoryException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getKeptItem", targetNamespace = "http://mdr.org/wsdl", className = "org.mdr.wsdl.GetKeptItem")
    @ResponseWrapper(localName = "getKeptItemResponse", targetNamespace = "http://mdr.org/wsdl", className = "org.mdr.wsdl.GetKeptItemResponse")
    public KeptItem getKeptItem(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0)
        throws RepositoryException_Exception
    ;

}
