
package org.mdr.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "RepositoryException", targetNamespace = "http://mdr.org/wsdl")
public class RepositoryException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private RepositoryException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public RepositoryException_Exception(String message, RepositoryException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public RepositoryException_Exception(String message, RepositoryException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.mdr.wsdl.RepositoryException
     */
    public RepositoryException getFaultInfo() {
        return faultInfo;
    }

}
